#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

# Retrieve arguments
app=$YNH_APP_INSTANCE_NAME
domain=$YNH_APP_ARG_DOMAIN

# Source app helpers and functions
source /usr/share/yunohost/helpers

# Check domain/path availability
sudo yunohost app checkurl "${domain}${path}" -a "$app" \
    || ynh_die "Path not available: ${domain}${path}"

INSTALL_CBLOG_PACKAGE
