#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -e

# Retrieve arguments
app=$YNH_APP_INSTANCE_NAME
domain=$YNH_APP_ARG_DOMAIN
path=$YNH_APP_ARG_PATH

# Source app helpers and functions
source /usr/share/yunohost/helpers
source functions.sh

# Check domain/path availability
sudo yunohost app checkurl "${domain}${path}" -a "$app" \
    || ynh_die "Path not available: ${domain}${path}"

YNH_PACKAGE_SRC=`pwd`

INSTALL_CBLOG_PACKAGE
INSTALL_NGINX_CONFIGURATION
